apiVersion: v1
kind: Service
metadata:
  name: pdf-service
  labels:
    app: pdf-service
spec:
  selector:
    app: pdf-service
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http

